-- Leiden Community Detection Schema
-- Stores hierarchical community detection results and summaries
-- Database: SQLite 3.37+

-- ============================================================================
-- 1. LEIDEN_COMMUNITIES TABLE
-- Stores entity membership in communities at different hierarchical levels
-- ============================================================================
CREATE TABLE IF NOT EXISTS leiden_communities (
    entity_id TEXT NOT NULL,                 -- References entities.unique_entity_id
    level TEXT NOT NULL,                     -- 'micro', 'meso', or 'macro'
    resolution REAL NOT NULL,                -- Resolution parameter γ used
    community_id INTEGER NOT NULL,           -- Community ID at this level
    modularity REAL,                         -- Modularity score of partition
    PRIMARY KEY (entity_id, level),
    FOREIGN KEY (entity_id) REFERENCES entities(unique_entity_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_leiden_level ON leiden_communities(level);
CREATE INDEX IF NOT EXISTS idx_leiden_community ON leiden_communities(community_id, level);
CREATE INDEX IF NOT EXISTS idx_leiden_entity ON leiden_communities(entity_id);

-- ============================================================================
-- 2. COMMUNITY_SUMMARIES TABLE
-- Stores natural language summaries of each community (generated by Gemini)
-- ============================================================================
CREATE TABLE IF NOT EXISTS community_summaries (
    community_key TEXT PRIMARY KEY,         -- Format: "level_resolution_communityid"
    level TEXT NOT NULL,                    -- 'micro', 'meso', or 'macro'
    resolution REAL NOT NULL,               -- Resolution parameter γ used
    community_id INTEGER NOT NULL,          -- Community ID
    summary TEXT NOT NULL,                  -- Natural language summary (2-3 sentences)
    entity_count INTEGER NOT NULL,          -- Number of entities in community
    relationship_count INTEGER,             -- Number of internal relationships
    top_entities TEXT,                      -- JSON array of most central entities
    avg_degree REAL,                        -- Average degree within community
    density REAL,                           -- Internal density of community
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_summary_level ON community_summaries(level);
CREATE INDEX IF NOT EXISTS idx_summary_community ON community_summaries(community_id, level);

-- ============================================================================
-- 3. LEIDEN_METADATA TABLE
-- Tracks when Leiden was last computed and graph state at that time
-- Single row table (enforced by CHECK constraint)
-- ============================================================================
CREATE TABLE IF NOT EXISTS leiden_metadata (
    id INTEGER PRIMARY KEY CHECK (id = 1), -- Enforce single row
    last_computed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_entities INTEGER NOT NULL,       -- Entity count when Leiden ran
    total_relationships INTEGER NOT NULL,  -- Relationship count when Leiden ran
    graph_density REAL,                    -- Overall graph density
    avg_degree REAL,                       -- Average node degree
    clustering_coefficient REAL,           -- Global clustering coefficient
    connected_components INTEGER,          -- Number of disconnected components
    resolutions TEXT NOT NULL,             -- JSON: {"micro": 2.0, "meso": 1.0, "macro": 0.5}
    computation_time_seconds REAL,        -- Time taken to compute
    notes TEXT                             -- Optional notes about this run
);

-- ============================================================================
-- 4. VIEWS FOR CONVENIENT QUERIES
-- ============================================================================

-- View: Entity with all community memberships
CREATE VIEW IF NOT EXISTS v_entity_communities AS
SELECT
    e.unique_entity_id,
    e.canonical_name,
    e.entity_type,
    lc_micro.community_id AS community_micro,
    lc_meso.community_id AS community_meso,
    lc_macro.community_id AS community_macro,
    lc_micro.resolution AS resolution_micro,
    lc_meso.resolution AS resolution_meso,
    lc_macro.resolution AS resolution_macro
FROM entities e
LEFT JOIN leiden_communities lc_micro ON e.unique_entity_id = lc_micro.entity_id AND lc_micro.level = 'micro'
LEFT JOIN leiden_communities lc_meso ON e.unique_entity_id = lc_meso.entity_id AND lc_meso.level = 'meso'
LEFT JOIN leiden_communities lc_macro ON e.unique_entity_id = lc_macro.entity_id AND lc_macro.level = 'macro';

-- View: Community summary with member count
CREATE VIEW IF NOT EXISTS v_community_details AS
SELECT
    cs.community_key,
    cs.level,
    cs.resolution,
    cs.community_id,
    cs.summary,
    cs.entity_count,
    cs.relationship_count,
    cs.density,
    cs.top_entities,
    COUNT(lc.entity_id) AS actual_member_count
FROM community_summaries cs
LEFT JOIN leiden_communities lc ON cs.level = lc.level AND cs.community_id = lc.community_id
GROUP BY cs.community_key;

-- ============================================================================
-- HELPER QUERIES FOR COMMON OPERATIONS
-- ============================================================================

-- Find entities in the same community as a given entity (at meso level)
-- Usage: Replace 'target_entity_id' with actual ID
/*
SELECT
    e.unique_entity_id,
    e.canonical_name,
    e.entity_type
FROM leiden_communities lc1
JOIN leiden_communities lc2 ON lc1.community_id = lc2.community_id AND lc1.level = lc2.level
JOIN entities e ON lc2.entity_id = e.unique_entity_id
WHERE lc1.entity_id = 'target_entity_id'
  AND lc1.level = 'meso'
  AND lc2.entity_id != 'target_entity_id';
*/

-- Get summary for a specific entity's community
/*
SELECT
    cs.summary,
    cs.entity_count,
    cs.top_entities
FROM leiden_communities lc
JOIN community_summaries cs ON lc.level = cs.level AND lc.community_id = cs.community_id
WHERE lc.entity_id = 'target_entity_id'
  AND lc.level = 'meso';
*/

-- Find cross-community connections (relationships spanning communities)
/*
SELECT
    r.relationship_type,
    e1.canonical_name AS from_entity,
    lc1.community_id AS from_community,
    e2.canonical_name AS to_entity,
    lc2.community_id AS to_community
FROM relationships r
JOIN entities e1 ON r.from_entity_id = e1.unique_entity_id
JOIN entities e2 ON r.to_entity_id = e2.unique_entity_id
JOIN leiden_communities lc1 ON r.from_entity_id = lc1.entity_id
JOIN leiden_communities lc2 ON r.to_entity_id = lc2.entity_id
WHERE lc1.level = 'meso'
  AND lc2.level = 'meso'
  AND lc1.community_id != lc2.community_id;
*/
